-- MySQL Script generated by MySQL Workbench
-- Sun Apr  7 20:37:57 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`FUNCIONARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FUNCIONARIOS` (
  `cod_fun` INT NOT NULL AUTO_INCREMENT,
  `nome_fun` VARCHAR(45) NOT NULL,
  `login_fun` VARCHAR(100) NOT NULL,
  `senha_fun` VARCHAR(200) NOT NULL,
  `telefone_fun` VARCHAR(12) NOT NULL,
  `montante` DOUBLE NULL,
  PRIMARY KEY (`cod_fun`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTES` (
  `cod_cli` INT NOT NULL AUTO_INCREMENT,
  `nome_cli` VARCHAR(45) NOT NULL,
  `login_cli` VARCHAR(100) NOT NULL,
  `senha_cli` VARCHAR(200) NOT NULL,
  `telefone_cli` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`cod_cli`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUTOS` (
  `id_pro` INT NOT NULL,
  `nome_pro` VARCHAR(45) NOT NULL,
  `tipo_pro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SERVICOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SERVICOS` (
  `cod_ser` INT NOT NULL,
  `nome_ser` VARCHAR(45) NOT NULL,
  `valor` DOUBLE NOT NULL,
  PRIMARY KEY (`cod_ser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AGENDAMENTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AGENDAMENTOS` (
  `cod_agen` INT NOT NULL,
  `FUNCIONARIOS_cod_fun` INT NOT NULL,
  `CLIENTES_cod_cli` INT NOT NULL,
  `PRODUTOS_id_pro` INT NULL,
  `SERVICOS_cod_ser` INT NOT NULL,
  PRIMARY KEY (`cod_agen`, `FUNCIONARIOS_cod_fun`, `CLIENTES_cod_cli`, `PRODUTOS_id_pro`, `SERVICOS_cod_ser`),
  INDEX `fk_AGENDAMENTOS_FUNCIONARIOS_idx` (`FUNCIONARIOS_cod_fun` ASC) VISIBLE,
  INDEX `fk_AGENDAMENTOS_CLIENTES1_idx` (`CLIENTES_cod_cli` ASC) VISIBLE,
  INDEX `fk_AGENDAMENTOS_PRODUTOS1_idx` (`PRODUTOS_id_pro` ASC) VISIBLE,
  INDEX `fk_AGENDAMENTOS_SERVICOS1_idx` (`SERVICOS_cod_ser` ASC) VISIBLE,
  CONSTRAINT `fk_AGENDAMENTOS_FUNCIONARIOS`
    FOREIGN KEY (`FUNCIONARIOS_cod_fun`)
    REFERENCES `mydb`.`FUNCIONARIOS` (`cod_fun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AGENDAMENTOS_CLIENTES1`
    FOREIGN KEY (`CLIENTES_cod_cli`)
    REFERENCES `mydb`.`CLIENTES` (`cod_cli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AGENDAMENTOS_PRODUTOS1`
    FOREIGN KEY (`PRODUTOS_id_pro`)
    REFERENCES `mydb`.`PRODUTOS` (`id_pro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AGENDAMENTOS_SERVICOS1`
    FOREIGN KEY (`SERVICOS_cod_ser`)
    REFERENCES `mydb`.`SERVICOS` (`cod_ser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
